@hostname = http://localhost:8080 

POST {{hostname}}/api/authentication/signup
content-type: application/json

{
  "userName": "Diketen",
  "firstName": "Diketen",
  "lastName":"Mavelon",
  "email":"diketen791@rabitex.com",
  "password":"adminN123"
}

###

POST {{hostname}}/api/authentication/signin
content-type: application/json

{
  "password":"adminN123",
  "email":"diketen791@rabitex.com"
}
###
POST {{hostname}}/api/authentication/check-email-exist
content-type: application/json

{
  "email":"jefersoncmnn@gmail.com"
}
###

POST {{hostname}}/api/authentication/send-verification-email-code
content-type: application/json

{
  "email":"diketen791@rabitex.com"
}
###

POST {{hostname}}/api/authentication/validate-verification-email-code
content-type: application/json

{
  "verificationEmailCode":"398585"
}

###

GET {{hostname}}/api/authentication//refresh-token